[package]
name = "wally"
version = "0.1.0"
authors = ["Rajasekharan Vengalil <avranju@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
structopt = "0.2"
url = "1.7"